---
# Push out the Ansible SSD key to my servers
- hosts: all

  tasks:

  - name: Placing key
    authorized_key: user=ansible key="{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}" state=present
